### ISSUE TITLE
ON-events not triggering?

### ISSUE THREAD

**Issue by draz88** [MetaLabs-inc/react-native-vimeo-iframe#19]
The events for onReady, onPlay, onProgress, and onFinish does not appear to be triggering.
Using the code from the example in the readme, no console logs are printed, tested on iOS 14.5 in emulator (I have not tested on Android).
```
onReady={() => console.log('Video is ready')}
onPlay={() => console.log('Video is playing')}
onPlayProgress={(data) => console.log('Video progress data:', data)}
onFinish={() => console.log('Video is finished')}
```

**Comment by mimi-uxui-dev** [comment]
Same issue on Android emulator @draz88 did you find a solution for this?

**Comment by draz88** [comment]
@mimi-uxui-dev, No, unfortunately not.

**Comment by mimi-uxui-dev** [comment]
the console log returns `about:blank`, any idea why ?

**Comment by Marcoo09** [comment]
Hi guys, thank you for the report. I'm going to take a look in detail the following days.

**Comment by draz88** [comment]
@Marcoo09, Have you had any chance to have a look at this?

**Comment by douglasrosa0110** [comment]
Here the same problem. Android, RN 0.66.2

**Comment by qsdamar** [comment]
Having the same issue, both on iOS and Android. None of the four events are being triggered.

**Comment by mimi-uxui-dev** [comment]
same for android emulator and android device

**Comment by fractalscape13** [comment]
same issue, all the "on" props don't work

**Comment by deltasamantha** [comment]
I also having the same issue both in iOs and Android platforms.

**Comment by douglasrosa0110** [comment]
https://github.com/conquer-plus/react-native-vimeo-iframe

**Comment by douglasrosa0110** [comment]
https://github.com/conquer-plus/react-native-vimeo-iframe

**Comment by GCnomore** [comment]
`src/template/index.ts`

```javascript
const  sendEvent = (evt, data) => {
  // Passes events through the bridge
  var payload = {
    name: evt,
    data: data
  };
  window.ReactNativeWebView.postMessage(JSON.stringify(payload));
}
```
This function is being called before its initialization.
Move it up and it works fine.

```javascript
var PLAYER_ID = 'player';

function webViewBridge() {
const vid = '${videoId}';
const isLooping = ${loop} ? '1' : '0';
const isAutoPlaying = ${autoPlay} ? '1' : '0';
const showControls = ${controls} ? '1' : '0';
const showSpeed = ${speed} ? '1' : '0';
const isMuted = ${muted} ? '1' : '0';

if (!vid) {
  return;
}

let iframe;
iframe = document.createElement('iframe');
iframe.src =
 'https://player.vimeo.com/video/' + vid + '?api=1' + '&autoplay=' + isAutoPlaying + '&loop=' + isLooping + '&controls=' + showControls  + '&speed=' + showSpeed +'&player_id=' + PLAYER_ID + '&muted=' + isMuted + '#t=${time}';
iframe.width = '100%';
iframe.height = '98%';
iframe.frameBorder = '0';
iframe.webkitallowfullscreen = true;
iframe.allowfullscreen = true;
iframe.mozallowfullscreen = true;
iframe.allow="autoplay;fullscreen"
iframe.id = PLAYER_ID;
document.body.appendChild(iframe);

const  sendEvent = (evt, data) => {
  // Passes events through the bridge
  var payload = {
    name: evt,
    data: data
  };
  window.ReactNativeWebView.postMessage(JSON.stringify(payload));
}

var player = $f(iframe);
player.addEvent('ready', function() {
  // Ideally we could just iterate over event names and add the sendEvent
  // handler to each of them, however that doesn't work because sendEvent
  // ends up just being called with whatever was the last event in the array.
  player.addEvent('play', function(data) {
    sendEvent('play', data);
  });
  player.addEvent('playProgress', function(data) {
    sendEvent('playProgress', data);
  });
  player.addEvent('pause', function(data) {
    sendEvent('pause', data);
  });
  player.addEvent('finish', function(data) {
    sendEvent('finish', data);
  });
  sendEvent('ready');
});

player.api(message, function(data) {
  sendEvent(message, data);
});
}

webViewBridge();
```

**Comment by jainAtish** [comment]
It works. Thanks a lot. @GCnomore

**Comment by zeusstl** [comment]
These trigger usually for me once I implemented the fix from @GCnomore, but believe or not, when I switch to some certain location, they stop triggering. Maybe it's related to some caching based on ip or maybe the internet is slower by some small amount or ???.

In other words, there seems to be some other factor in whether the events fire properly.

**Comment by GCnomore** [comment]
@zeusstl This was while ago and out team decided not to apply `onMessage` event so I can't 100% remember what I went through but I also did have problem after this fix too. I did some more fixes but the only thing I can remember is that if it is android that's having problem, check out Proguard.
[https://www.androidbugfix.com/2022/01/proguard-stops-javascript-in-webview.html](https://www.androidbugfix.com/2022/01/proguard-stops-javascript-in-webview.html)

**Comment by felipe-najson** [comment]
Hey guys, thank you for reporting this, we will be publishing the new version of the library these days that solves event triggering for Android. For a reason I still don't know the events are not triggered for iOS. I will try to solve it for this platform when I have more time.

Regards, Philip

**Comment by zeusstl** [comment]
@felipe-najson Submitted a pr with a fix for IOS events not firing. I have not tested how this affects Android, but the changes are pretty minor.

**Comment by felipe-najson** [comment]
Thanks, @zeusstl I just merged your pr, proceed to close this issue.
